version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data
      - ./database-config/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
volumes:
  database-data: {}
