version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 80:8080
    volumes:
      - ./:/user/src/app
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
